### ISSUE TITLE
2024-11-02网站查询已经不再返回json数据了

### ISSUE THREAD

**Issue by jiafengwang** [tangffntr/yncx#2]
2024-11-02网站查询已经不再返回json数据了，应该是混淆加密了
![PixPin_2024-11-02_21-06-13](https://github.com/user-attachments/assets/0fb40226-ae6b-4947-a94c-e34893a811f6)

**Comment by tangffntr** [comment]
是的加密了，看了下是SM2加密，直接模拟下就行了
